"""Terminal image-output format drivers."""

python_bootstrap_library(
    name = "finalize",
    srcs = ["finalize.py"],
)

python_bootstrap_binary(
    name = "archive",
    main = "archive.py",
    deps = [
        "//archive:cpio",
        "//rootfs:rootfs",
        ":finalize",
    ],
    visibility = ["PUBLIC"],
)

python_bootstrap_binary(
    name = "disk",
    main = "disk.py",
    deps = [
        "//rootfs:rootfs",
        ":finalize",
    ],
    visibility = ["PUBLIC"],
)

python_bootstrap_binary(
    name = "convert",
    main = "convert.py",
    visibility = ["PUBLIC"],
)

python_bootstrap_binary(
    name = "rpmdb",
    main = "rpmdb.py",
    deps = ["//rootfs:rootfs"],
    visibility = ["PUBLIC"],
)

python_bootstrap_binary(
    name = "sbom",
    main = "sbom.py",
    deps = ["//rootfs:rootfs"],
    visibility = ["PUBLIC"],
)

python_bootstrap_binary(
    name = "sysext",
    main = "sysext.py",
    deps = [
        "//rootfs:rootfs",
        ":finalize",
    ],
    visibility = ["PUBLIC"],
)
