"""Terminal image-output format drivers."""

python_bootstrap_binary(
    name = "archive",
    main = "archive.py",
    deps = [
        "//:specs",
        "//:util",
        "//archive:cpio",
        "//image:finalize",
    ],
    visibility = ["PUBLIC"],
)

python_bootstrap_binary(
    name = "disk",
    main = "disk.py",
    deps = [
        "//:specs",
        "//image:finalize",
    ],
    visibility = ["PUBLIC"],
)

python_bootstrap_binary(
    name = "convert",
    main = "convert.py",
    deps = ["//:specs"],
    visibility = ["PUBLIC"],
)

python_bootstrap_binary(
    name = "sysext",
    main = "sysext.py",
    deps = [
        "//:specs",
        "//:util",
        "//image:finalize",
        "//rootfs:rootfs",
    ],
    visibility = ["PUBLIC"],
)
