"""The core kernel modules a UKI's per-kernel initrd carries by default.

Only the path to `/usr` has to work from the UKI; `/usr` itself keeps every module the kernel package
installs, so anything missing here is still loadable once the system has switched root.

Data only, and it stays that way: tine//tests:unit-test reads this file to pin what the list selects.
"""

DEFAULT_INITRD_MODULES = [
    "ahci",
    "amd_atl",
    "amd_ctl",
    "amd-pmc",
    "amd64_edac",
    "atkbd",
    "autofs4",
    "binfmt_misc",
    "btrfs",
    "cdrom",
    "cfg80211",
    "configfs",
    "crc-ccitt",
    "dm-crypt",
    "dm-integrity",
    "dm-mod",
    "dm-multipath",
    "dm-raid",
    "dm-verity",
    "dmi-sysfs",
    "edac_mce_amd",
    "efi-pstore",
    "efivarfs",
    "erofs",
    "evdev",
    "ext4",
    "firmware_attributes_class",
    "hid-generic",
    "i2c-algo-bit",
    "i2c_hid_acpi",
    "i2c-mux",
    "i2c-smbus",
    "i8042",
    "intel_pmc_ssram_telemetry",
    "intel_rapl_common",
    "intel-uncore-frequency-common",
    "intel-vsec",
    "kvm",
    "libphy",
    "loop",
    "mdio_devres",
    "mei",
    "nvme",
    "nvmet-tcp",
    "overlay",
    "parport",
    "platform_profile",
    "pmt_telemetry",
    "qemu_fw_cfg",
    "raid[0-9]*",
    "rapl",
    "scsi_mod",
    "sd_mod",
    "sr_mod",
    "serio",
    "sg",
    "skx_edac_common",
    "squashfs",
    "thunderbolt_net",
    "tpm_tis",
    "tpm_vtpm_proxy",
    "typec_ucsi",
    "ucsi_acpi",
    "usbhid",
    "usb-storage",
    "vfat",
    "video",
    "virtio_balloon",
    "virtio_blk",
    "virtio_console",
    "virtio_dma_buf",
    "virtio_mmio",
    "virtio_net",
    "virtio_pci",
    "virtio_scsi",
    "virtio-rng",
    "virtiofs",
    "vmd",
    "vmw_vsock_virtio_transport",
    "vsock",
    "watchdog",
    "wmi",
    "wmi-bmof",
    "x_tables",
    "xfs",
    "xhci-pci-renesas",
    "fs/nls/",
    "crypto/",
    # specialized hardware, minus the AMD accelerator every Ryzen has
    "-drivers/crypto/",
    "ccp_crypto",
    # for early/systemd-zram-setup
    "zram",
    # for firewalld.service
    "nfnetlink",
]
