"""buckify — the format-independent host orchestrator for (re)generating a catalog.

Runs on the host (a python_bootstrap_binary), invoked via `buck run
@tine//distribution:buckify -- --catalog-dir <dir> --buck <buck>`. It does NOT
resolve packages itself; it drives the per-distribution, per-format resolvers:

  1. `buck uquery` to find the `catalog//:<distribution>.buckify` resolve targets (each a
     chroot_python_binary bound to *that distribution's* engine root by
     declare_catalog — Arch in the Arch engine, Fedora in the Fedora engine).
  2. for each, nest `buck run <target> -- resolve --distribution <distribution> --catalog-dir
     <dir>`, which writes the fragment <dir>/<distribution>.json in that distribution's engine.
  3. amalgamate the fragments into <dir>/generated.bzl (static loads of each fragment's
     `value` + one dict).
  4. scaffold <dir>/BUCK if absent, so a catalog authored with only a manifest is
     buildable after one run.

Nested buck is supported: a `buck run` target executes with cwd = the invocation
dir and inherits PATH + BUCK_ISOLATION_DIR, so a child `buck` reuses the same
daemon (verified against the buck source). The buck binary is passed in (--buck)
because this is a python child, not buck itself (buck finds *itself* via
current_exe, which a python process can't use).
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path

# Starting BUCK for a freshly-created catalog directory: declare its distributions via
# tine's macro. Scaffolded only when absent (the orchestrator never clobbers an edited
# one); kept in sync with tine/catalog/BUCK.
_CATALOG_BUCK = """\
# Scaffolded by `buckify`; safe to edit. Declares this catalog's distributions — tine
# provides the declare_catalog macro + rules.
load("@tine//defs:catalog.bzl", "declare_catalog")
load(":generated.bzl", "DISTRIBUTIONS")

declare_catalog(DISTRIBUTIONS)
"""


def _alias(name: str) -> str:
    """A valid Starlark identifier for a distribution's amalgamation load binding."""
    return "_" + re.sub(r"\W", "_", name)


def _resolve_targets(buck: str) -> list[str]:
    """The <distribution>.buckify resolve targets in the active catalog cell."""
    out = subprocess.run(
        [buck, "uquery", "kind('chroot_python_binary', catalog//...)"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    return sorted(t for t in out.split() if t.endswith(".buckify"))


def _distribution_of(target: str) -> str:
    return target.rsplit(":", 1)[1].removesuffix(".buckify")


def _resolve(buck: str, target: str, catalog_dir: Path) -> None:
    distribution = _distribution_of(target)
    print(f"==> resolving {distribution} in its engine (via {target})", file=sys.stderr)
    # `-v 0 --console none` mutes buck's own wrapper output (build id, "BUILD SUCCEEDED",
    # network) for the nested run; the resolver's progress on stderr still comes through.
    subprocess.run(
        [
            buck,
            "-v",
            "0",
            "run",
            target,
            "--console",
            "none",
            "--",
            "resolve",
            "--distribution",
            distribution,
            "--catalog-dir",
            str(catalog_dir),
        ],
        check=True,
    )


def amalgamate(catalog_dir: Path) -> None:
    """Write generated.bzl merging the per-distribution JSON fragments into one
    `DISTRIBUTIONS` dict."""
    names = sorted(p.stem for p in catalog_dir.glob("*.json"))
    lines = [
        "# @" + "generated by `buckify` — do not edit.",
        "# Amalgamation: loads each per-distribution JSON fragment's `value` (buck decodes",
        "# JSON/TOML natively at load time) and merges them into one DISTRIBUTIONS dict. The",
        "# fragments are written by the per-distribution resolvers, each in its own engine.",
        "",
        *[f'load(":{n}.json", {_alias(n)} = "value")' for n in names],
        "",
        "DISTRIBUTIONS = {",
        *[f'    "{n}": {_alias(n)},' for n in names],
        "}",
        "",
    ]
    out = catalog_dir / "generated.bzl"
    out.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"==> amalgamated {len(names)} fragments → {out}", file=sys.stderr)


def scaffold(catalog_dir: Path) -> None:
    buck = catalog_dir / "BUCK"
    if buck.exists():
        return
    buck.write_text(_CATALOG_BUCK, encoding="utf-8", newline="\n")
    print(f"==> scaffolded {buck}", file=sys.stderr)


def main(argv: list[str] | None = None) -> None:
    p = argparse.ArgumentParser(prog="buckify")
    p.add_argument("--catalog-dir", required=True, help="catalog dir to (re)generate")
    p.add_argument("--buck", default="buck", help="buck binary to nest (default: PATH)")
    p.add_argument(
        "--distribution",
        action="append",
        help="only (re)resolve these distributions; default: all in the active catalog",
    )
    args = p.parse_args(argv)
    catalog_dir = Path(args.catalog_dir)

    targets = _resolve_targets(args.buck)
    if args.distribution:
        targets = [t for t in targets if _distribution_of(t) in set(args.distribution)]
    if not targets:
        raise SystemExit("buckify: no <distribution>.buckify resolve targets found in catalog//...")

    for target in targets:
        _resolve(args.buck, target, catalog_dir)
    amalgamate(catalog_dir)
    scaffold(catalog_dir)


if __name__ == "__main__":
    main()
