# @generated by `buckify` — do not edit.
# Amalgamation: loads each per-distribution JSON fragment's `value` (buck decodes
# JSON/TOML natively at load time) and merges them into one DISTRIBUTIONS dict. The
# fragments are written by the per-distribution resolvers, each in its own engine.

load(":centos10.json", _centos10 = "value")
load(":fedora44.json", _fedora44 = "value")
load(":rawhide.json", _rawhide = "value")

DISTRIBUTIONS = {
    "centos10": _centos10,
    "fedora44": _fedora44,
    "rawhide": _rawhide,
}
