"""The user-facing tine command."""

python_bootstrap_library(
    name = "box",
    deps = [":workspace"],
    srcs = ["box.py"],
)

python_bootstrap_library(
    name = "workspace",
    deps = ["//:util"],
    srcs = [
        "errors.py",
        "workspace.py",
    ],
)

python_bootstrap_binary(
    name = "tine",
    main = "__main__.py",
    deps = [
        ":box",
        ":workspace",
    ],
)
