"""Shared archive primitives."""

python_bootstrap_library(
    name = "cpio",
    srcs = ["cpio.py"],
    visibility = ["tine//..."],
)

export_file(
    name = "cpio-src",
    src = "cpio.py",
    visibility = ["tine//tests:unit-test"],
)
