"""Shared archive primitives."""

load("//python:defs.bzl", "tine_python_library")

tine_python_library(
    name = "cpio",
    srcs = ["cpio.py"],
    visibility = ["tine//..."],
    deps = ["//:util"],
)
