"""Development-box smoke target."""

load("@tine//box:defs.bzl", "box")

box.new(
    name = "demo.box",
    packages = [
        "bash",
        "coreutils",
        "fish",
    ],
    release = "tine//catalog:fedora.rawhide.release",
)
