"""Native package systems, repositories, releases, managers, and buildroots."""

python_bootstrap_library(
    name = "href",
    srcs = ["href.py"],
    visibility = ["PUBLIC"],
)

python_bootstrap_library(
    name = "installer",
    srcs = ["installer.py"],
    deps = ["//:specs", "//rootfs:rootfs"],
    visibility = ["PUBLIC"],
)

python_bootstrap_library(
    name = "transaction",
    srcs = ["transaction.py"],
    deps = ["//:util"],
    visibility = ["PUBLIC"],
)
