name: bump

on:
  schedule:
    # quiet hours on Sundays, ready at the start of the work week
    - cron: '17 4 * * 0'
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: bump

jobs:
  bump:
    uses: ./.github/workflows/bot-pr.yml
    with:
      name: bump
      label-description: automatic version bumps
      command: bin/tine buck run tine//tools:bump -- --all --commit
