"""Logical image mutation and boot assembly drivers."""

python_bootstrap_binary(
    name = "layer",
    main = "layer.py",
    deps = [
        "//:util",
        "//rootfs:rootfs",
    ],
    visibility = ["PUBLIC"],
)

python_bootstrap_binary(
    name = "uki",
    main = "uki.py",
    deps = [
        ":finalize",
        "//archive:cpio",
    ],
    visibility = ["PUBLIC"],
)

python_bootstrap_library(
    name = "finalize",
    srcs = ["finalize.py"],
    deps = ["//rootfs:rootfs"],
    visibility = ["PUBLIC"],
)

python_bootstrap_library(
    name = "artifacts-lib",
    srcs = ["artifacts.py"],
    deps = [
        ":finalize",
        "//:util",
    ],
)

python_bootstrap_binary(
    name = "artifacts",
    main = "artifacts.py",
    deps = [
        ":finalize",
        "//:util",
    ],
    visibility = ["PUBLIC"],
)

python_bootstrap_binary(
    name = "boot",
    main = "boot.py",
    deps = [
        ":artifacts-lib",
        ":finalize",
        "//vendor:mkosi",
    ],
    visibility = ["PUBLIC"],
)
