"""Logical image mutation and boot assembly drivers."""

python_bootstrap_binary(
    name = "layer",
    main = "layer.py",
    deps = [
        "//:util",
        "//rootfs:rootfs",
    ],
    visibility = ["PUBLIC"],
)

python_bootstrap_binary(
    name = "uki",
    main = "uki.py",
    deps = [
        "//archive:cpio",
        "//rootfs:rootfs",
    ],
    visibility = ["PUBLIC"],
)

python_bootstrap_binary(
    name = "boot-artifacts",
    main = "boot_artifacts.py",
    deps = [
        "//:util",
        "//rootfs:rootfs",
    ],
    visibility = ["PUBLIC"],
)
